### ISSUE TITLE
Wrong scheme in tarball link for UI

### ISSUE THREAD

**Issue by stek29** [verdaccio/verdaccio#1714]
**Describe the bug**

When verdaccio is accessed via HTTPS, dist.tarball urls are returned with wrong scheme (http instead of https) to UI (api uri: `/-/verdaccio/packages`)

**To Reproduce**

1. Serve verdaccio via https
2. Try to download a package tarball

**Expected behavior**
Tarball is downloaded

**Actual behavior**
Tarball tries to be downloaded via http, which violates CSP (`connect-src self`).

**Environment information**

verdaccio --info: (cpu removed)
Environment Info:
  System:
    OS: Linux 4.19 Alpine Linux
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm

verdaccio version: 4.4.2

It's running in kubernetes cluster from a custom image based on `verdaccio:4.4.2` and exposed via ingress.

**Additional information:**
I think this is not UI bug but rather backend bug since tarball url shown by `npm show` has correct scheme (https).

**Comment by juanpicado** [comment]
I think that was fixed in the last release (few days ago) try with the latest one please.

**Comment by stek29** [comment]
Oh, I didn’t notice 4.4.3 was released. Sorry, I’ll try with 4.4.3.

**Comment by stek29** [comment]
nope, updated to 4.4.3 and it's not fixed.
i've also verified that `@verdaccio/ui-theme` is 4.4.3 too:

```sh
~ $ cat package.json  | grep '"version"'
  "version": "4.4.3",
~ $ cat node_modules/@verdaccio/ui-theme/package.json | grep '"version"'
  "version": "0.3.13",
```

**Comment by stek29** [comment]
I'm not sure it's UI bug and i don't get how updating ui-theme could've fixed it:

If you go to main page, you'll see this request in network tab:
https://npm.example.com/-/verdaccio/packages: `.[].dist.tarball` starts with http://npm.example.com

If you open any package, you'll see this request in network tab:
https://npm.example.com/-/verdaccio/sidebar/package: both `.latest.dist.tarball` and `.versions[].dist.tarball` starts with https://npm.example.com

**Comment by juanpicado** [comment]
I confirm the bug, thanks for the report. 

![Screen Shot 2020-02-20 at 8 08 05 PM](https://user-images.githubusercontent.com/558752/74969383-c8a07d80-541c-11ea-9992-a4cafea4bb64.png)



`npm show @juanpicado/registry_test`

```
@juanpicado/registry_test@1.0.3-0f84c69-pr10.0 | MIT | deps: none | versions: 40
https://github.com/juanpicado/registry_test#readme

dist
.tarball: https://registry.verdaccio.org/@juanpicado%2fregistry_test/-/registry_test-1.0.3-0f84c69-pr10.0.tgz
.shasum: adb901870ec7dafd9a49ea99644bc7f4de58d170
.integrity: sha512-KE6iRkFQaZygdrtJZjuDJiuVjAiTHEGMcIVhwa6A8RXBOutMtjlpMyZtJ3w7GErm7TcUFpFmrkuSgKQTAmRspA==

dist-tags:
latest: 1.0.3-0f84c69-pr10.0  
```

Via API I get `https` while via web I got `http`.

**Comment by coolsp** [comment]
Thanks @stek29 
I noticed the same issue based on a report (on a closed issue) in verdaccio/ui: _Cannot download tarball after logging in # 75_.
Right when I had a fix and wanted to create a PR I noticed this.  The fix is similar but I had opted to leave `processPermissionsPackages` as is and add a second loop before the `next`.
E.g. In `src/api/web/endpoint/packages.ts` for route `/packages`:
```TypeScript
      // Convert the tarball URI to reflect the registry URL being used
      for (const pkg of packages) {
        pkg.dist.tarball = getLocalRegistryTarballUri(pkg.dist.tarball, pkg.name, req, config.url_prefix);
      }
```
