### ISSUE TITLE
Publishing scoped package does not work due to slash escape, even when not using reverse proxy

### ISSUE THREAD

**Issue by bayareacoder** [verdaccio/verdaccio#2096]
**Describe the bug**
After updating Verdaccio to latest version (4.11.0), publishing a scoped package with latest version of Verdaccio does not work due to "/" being escaped
This has been reported before (see #1778) occurring when Verdaccio is used behind a reverse proxy, but in my case this happens with the default install and starting Verdaccio from the CLI, per: https://verdaccio.org/docs/en/installation
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT http://<domain>/@<scope>%2f<package> - no such package available
npm ERR! 404 
npm ERR! 404  '@<scope>/<package>@1.2.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Expected behavior**
Should be able to install scoped package...

**Workaround**
I reverted to an older version (4.0.3) and it works with that.

**Comment by juanpicado** [comment]
Please provide more info, detail helps to reproduce. Please read the template.

**Comment by bayareacoder** [comment]
Environment:
- MacOS with Verdaccio 4.11
- start from CLI
- server reached from public internet via DDNS and port forwarding on router
- issue NPM publish of a scoped package
- error shown in original post shows root Verdaccio showing a PUT request with slash escape
- this issue only appeared after Verdaccio upgrade. Reverting to 4.3 resolved the issue proving there is a regression.

**Comment by takhello** [comment]
http <-- 404, user: user-name(127.0.0.1), req: 'PUT /package-name, error: no such package available
 
 -------------------------------- -------------------------------- --------------------------------
 verdaccio -V:
 4.11.3

**Comment by FallingSnow** [comment]
I'm experiencing this too. Using verdaccio 4.16.0 behind a traefik proxy, both on docker.
Server logs are below:
```js
 http --- 172.21.0.10 requested 'PUT /-/user/org.couchdb.user:admin/-rev/undefined'
 http --- 201, user: admin(108.162.215.152 via 172.21.0.10), req: 'PUT /-/user/org.couchdb.user:admin/-rev/undefined', bytes: 197/648
 http --- 172.21.0.10 requested 'PUT /@<scope>%2f<package>'
 info --- auth/allow_action: access granted to: undefined
 info --- admin is allowed publish for @<scope>/<package>
 http --- 404, user: admin(172.69.35.213 via 172.21.0.10), req: 'PUT /@<scope>%2f<package>', error: no such package available
 http --- 172.21.0.10 requested 'GET /'
 http --- 200, user: null(172.68.133.66 via 172.21.0.10), req: 'GET /', bytes: 0/476
 http --- 172.21.0.10 requested 'GET /-/verdaccio/packages'
 http --- 304, user: null(172.68.133.66 via 172.21.0.10), req: 'GET /-/verdaccio/packages', bytes: 0/0
```

**Comment by FallingSnow** [comment]
Tracked it down to an error in `node_modules/verdaccio/build/api/endpoint/api/publish.js` so far.
Error is triggered by the call to 
```js
createTarball(_path.default.basename(firstAttachmentKey), _attachments[firstAttachmentKey], function (error) {
```

Error:
```js
NotFoundError: no such package available
    at getError (/home/node/app/node_modules/@verdaccio/commons-api/lib/index.js:113:45)
    at Object.getNotFound (/home/node/app/node_modules/@verdaccio/commons-api/lib/index.js:147:10)
    at /home/node/app/node_modules/verdaccio/build/lib/local-storage.js:681:44
    at /home/node/app/node_modules/@verdaccio/local-storage/lib/local-fs.js:190:14 {
  code: 404
}
```

**Comment by FallingSnow** [comment]
Seems to be coming from `node_modules/verdaccio/build/lib/local-storage.js`
```js
    storage.readPackage(name, (err, result) => {
      if (err) {
        if (err.code === _constants.STORAGE.NO_SUCH_FILE_ERROR || err.code === _constants.HTTP_STATUS.NOT_FOUND) {
          return callback(_utils.ErrorCode.getNotFound());
```

and/or `node_modules/verdaccio/build/lib/storage.js`:
```js
return callback(_utils.ErrorCode.getNotFound(_constants.API_ERROR.NO_PACKAGE), null, upLinksErrors);
```

Both of these were called when the error happens.

That's all the time I can spend on this.

**Comment by juanpicado** [comment]
Thanks @FallingSnow :) I'll take it from here, thanks for the debugging session, I'll finish my PR #2447 then move on to this one see what I get.

**Comment by juanpicado** [comment]
I'd need more data, I cannot reproduce. This is my package.

```
{
  "name": "@scope/test_pkg",
  "version": "2.0.5",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "^4.17.21"
  }
}
```
This is what I see on the local storage
```
{
	"name": "@scope/test_pkg",
	"versions": {
		"2.0.5": {
			"name": "@scope/test_pkg",
			"version": "2.0.5",
			"description": "",
			"main": "index.js",
			"scripts": {
				"test": "echo \"Error: no test specified\" && exit 1"
			},
			"keywords": [],
			"author": "",
			"license": "ISC",
			"dependencies": {
				"lodash": "^4.17.21"
			},
			"_id": "@scope/test_pkg@2.0.5",
			"_nodeVersion": "14.17.4",
			"_npmVersion": "7.21.0",
			"dist": {
				"integrity": "sha512-DLq02SatQ0KRrp2uiyVz2O9HAmde+ZNwGAICoxR/LP+ku/Zu2tu8BkZP/+4wESkKwhLKez+7//13FVeW0ynvqg==",
				"shasum": "5f1fc1f26cd0431207c60323486aa74e271c41c6",
				"tarball": "http://localhost:4873/@scope/test_pkg/-/@scope/test_pkg-2.0.5.tgz"
			},
			"contributors": []
		}
	},
	"time": {
		"modified": "2021-09-26T06:59:29.678Z",
		"created": "2021-09-26T06:59:29.678Z",
		"2.0.5": "2021-09-26T06:59:29.678Z"
	},
	"users": {},
	"dist-tags": {
		"latest": "2.0.5"
	},
	"_uplinks": {},
	"_distfiles": {},
	"_attachments": {
		"test_pkg-2.0.5.tgz": {
			"shasum": "5f1fc1f26cd0431207c60323486aa74e271c41c6",
			"version": "2.0.5"
		}
	},
	"_rev": "3-5f675ec8006be776",
	"_id": "@scope/test_pkg",
	"readme": "ERROR: No README data found!"
}
```
This i what I see on the server side
````
 http --- 127.0.0.1 requested 'PUT /@scope%2ftest_pkg'
 info --- auth/allow_action: access granted to: undefined
 info --- test is allowed publish for @scope/test_pkg
 info --- making request: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg'
 http --- 404, req: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg' (streaming)
 http --- 404, req: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg', bytes: 0/21
 http --- 201, user: test(127.0.0.1), req: 'PUT /@scope%2ftest_pkg', bytes: 1208/53
 http --- 127.0.0.1 requested 'PUT /@scope%2ftest_pkg'
 info --- auth/allow_action: access granted to: undefined
 info --- test is allowed publish for @scope/test_pkg
 info --- making request: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg'
 http --- 404, req: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg' (streaming)
 http --- 404, req: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg', bytes: 0/21
 http --- 201, user: test(127.0.0.1), req: 'PUT /@scope%2ftest_pkg', bytes: 1208/53
 http --- 127.0.0.1 requested 'GET /lodash'
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for lodash
 info --- making request: 'GET https://registry.npmjs.org/lodash'
 http --- 200, req: 'GET https://registry.npmjs.org/lodash' (streaming)
 http --- 200, req: 'GET https://registry.npmjs.org/lodash', bytes: 0/209548
 http --- 200, user: test(127.0.0.1), req: 'GET /lodash', bytes: 0/22368
 http --- 127.0.0.1 requested 'GET /@scope%2ftest_pkg'
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for @scope/test_pkg
 info --- making request: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg'
 http --- 404, req: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg' (streaming)
 http --- 404, req: 'GET https://registry.npmjs.org/@scope%2Ftest_pkg', bytes: 0/21
 http --- 200, user: test(127.0.0.1), req: 'GET /@scope%2ftest_pkg', bytes: 0/590
 http --- 127.0.0.1 requested 'POST /-/npm/v1/security/advisories/bulk'
 http --- 200, user: null(127.0.0.1), req: 'POST /-/npm/v1/security/advisories/bulk', bytes: 68/2
```
And my package manager
```
npm --version
7.21.0
```

The package publish and install just fine. 

You might need to be more specific, which package managers, versions, which v4 actually broke this, from 4.0.3 to 5.x is a really wide range. Also a project example would be useful.

**Comment by FallingSnow** [comment]
```
pnpm --version
6.15.1
```
```
$ pnpm publish --no-git-checks
0 verbose cli [
0 verbose cli   '/home/ayrton/.nvm/versions/node/v16.7.0/bin/node',
0 verbose cli   '/home/ayrton/.nvm/versions/node/v16.7.0/bin/npm',
0 verbose cli   'publish',
0 verbose cli   '--ignore-scripts',
0 verbose cli   '<scope>-<package>-0.1.0.tgz',
0 verbose cli   '--no-git-checks'
0 verbose cli ]
1 info using npm@7.20.3
2 info using node@v16.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/ayrton/Coding/node/diablodollars/packages/<package>/.npmrc Completed in 1ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:/home/ayrton/.npmrc Completed in 3ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:/home/ayrton/.nvm/versions/node/v16.7.0/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 26ms
19 timing npm:load:configload Completed in 26ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 3ms
22 timing npm:load:cleanupLog Completed in 5ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 38ms
26 timing config:load:flatten Completed in 7ms
27 verbose publish [ '<scope>-<package>-0.1.0.tgz' ]
28 notice
29 notice 📦  @<scope>/<package>@0.1.0
30 notice === Tarball Contents ===
31 notice 5.5kB Cargo.lock
31 notice 419B  Cargo.toml
31 notice 584B  index.js
31 notice 572B  package.json
31 notice 1.5kB src/lib.rs
31 notice 272B  src/test.rs
32 notice === Tarball Details ===
33 notice name:          @<scope>/<package>
33 notice version:       0.1.0
33 notice filename:      @<scope>/<package>-0.1.0.tgz
33 notice package size:  3.1 kB
33 notice unpacked size: 8.8 kB
33 notice shasum:        57157c0f21da8f576f4cb46b71277579049e821a
33 notice integrity:     sha512-fd/+RCLhlMAlT[...]me9m7wY5PL/cA==
33 notice total files:   6
34 notice
35 timing command:publish Completed in 490ms
36 verbose stack HttpErrorGeneral: 404 Not Found - PUT https://js.universalis.dev/@<scope>%2f<package> - no such package available
36 verbose stack     at /home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
36 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
36 verbose stack     at async publish (/home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/node_modules/libnpmpublish/publish.js:43:12)
36 verbose stack     at async Publish.publish (/home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/lib/publish.js:120:7)
37 verbose statusCode 404
38 verbose pkgid @<scope>/<package>@0.1.0
39 verbose cwd [redacted]/<package>
40 verbose Linux 5.14.7-arch1-1
41 verbose argv "/home/ayrton/.nvm/versions/node/v16.7.0/bin/node" "/home/ayrton/.nvm/versions/node/v16.7.0/bin/npm" "publish" "--ignore-scripts" "<scope>-<package>-0.1.0.tgz" "--no-git-checks"
42 verbose node v16.7.0
43 verbose npm  v7.20.3
44 error code E404
45 error 404 Not Found - PUT https://[redacted]/@<scope>%2f<package> - no such package available
46 error 404
47 error 404 '@<scope>/<package>@0.1.0' is not in the npm registry.
48 error 404 You should bug the author to publish it (or use the name yourself!)
49 error 404 Note that you can also install from a
50 error 404 tarball, folder, http url, or git url.
51 verbose exit 1
```

My config:
```
storage: ./storage
auth:
  ldap:
    type: ldap
    # Only required if you are fetching groups that do not have a "cn" property. defaults to "cn" 
    #groupNameAttribute: "ou"
    # Optional, default false. 
    cache:
      # max credentials to cache (default to 100 if cache is enabled) 
      size: 100
      # cache expiration in seconds (default to 300 if cache is enabled) 
      expire: 300
    client_options:
      url: "ldaps://ldap.universalis.io"
      # Only required if you need auth to bind 
      adminDn: "cn=readonly,dc=universalis,dc=io"
      adminPassword: "/9i;t)iV0b>jN:rLwIe(;}?QE1;n0R"
      # Search base for users 
      searchBase: "ou=users,dc=universalis,dc=io"
      searchFilter: "(uid={{username}})"
      # If you are using groups, this is also needed 
      groupDnProperty: 'cn'
      groupSearchBase: 'ou=groups,dc=universalis,dc=io'
      # If you have memberOf support on your ldap 
      searchAttributes: ['*', 'memberOf']
      # Else, if you don't (use one or the other): 
      # groupSearchFilter: '(memberUid={{dn}})' 
      # Optional 
      reconnect: true
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@diablo-dollars/*":
    access: $authenticated
    publish: $authenticated
  "@universalis/*":
    access: $authenticated
    publish: $authenticated
  "**":
    proxy: npmjs
logs:
  - { type: stdout, fromat: pretty, level: http }
web:
  enable: true
  title: Universalis
  logo: logo.png
  scope: universalis
#http_proxy: http://universalis.dev
#https_proxy: https://universalis.dev
listen:
  - 0.0.0.0:4873
security:
```

**Comment by juanpicado** [comment]
Please clean your config ;)

**Comment by FallingSnow** [comment]
Lol, I pressed ctrl+enter to add a line above and it submitted it. Sorry, thank you!

**Comment by juanpicado** [comment]
Better remove it and read it, edit comments are visible over time.

**Comment by FallingSnow** [comment]
Brb, gotta change some passwords lol.

**Comment by FallingSnow** [comment]
Lesson learned, don't clean configs in the browser.

```
pnpm --version
6.15.1
```
```
$ pnpm publish --no-git-checks
0 verbose cli [
0 verbose cli   '/home/ayrton/.nvm/versions/node/v16.7.0/bin/node',
0 verbose cli   '/home/ayrton/.nvm/versions/node/v16.7.0/bin/npm',
0 verbose cli   'publish',
0 verbose cli   '--ignore-scripts',
0 verbose cli   '<scope>-<package>-0.1.0.tgz',
0 verbose cli   '--no-git-checks'
0 verbose cli ]
1 info using npm@7.20.3
2 info using node@v16.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/ayrton/Coding/node/[redacted]/packages/<package>/.npmrc Completed in 1ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:/home/ayrton/.npmrc Completed in 3ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:/home/ayrton/.nvm/versions/node/v16.7.0/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 26ms
19 timing npm:load:configload Completed in 26ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 3ms
22 timing npm:load:cleanupLog Completed in 5ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 38ms
26 timing config:load:flatten Completed in 7ms
27 verbose publish [ '<scope>-<package>-0.1.0.tgz' ]
28 notice
29 notice 📦  @<scope>/<package>@0.1.0
30 notice === Tarball Contents ===
31 notice 5.5kB Cargo.lock
31 notice 419B  Cargo.toml
31 notice 584B  index.js
31 notice 572B  package.json
31 notice 1.5kB src/lib.rs
31 notice 272B  src/test.rs
32 notice === Tarball Details ===
33 notice name:          @<scope>/<package>
33 notice version:       0.1.0
33 notice filename:      @<scope>/<package>-0.1.0.tgz
33 notice package size:  3.1 kB
33 notice unpacked size: 8.8 kB
33 notice shasum:        57157c0f21da8f576f4cb46b71277579049e821a
33 notice integrity:     sha512-fd/+RCLhlMAlT[...]me9m7wY5PL/cA==
33 notice total files:   6
34 notice
35 timing command:publish Completed in 490ms
36 verbose stack HttpErrorGeneral: 404 Not Found - PUT https://[redacted]/@<scope>%2f<package> - no such package available
36 verbose stack     at /home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
36 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
36 verbose stack     at async publish (/home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/node_modules/libnpmpublish/publish.js:43:12)
36 verbose stack     at async Publish.publish (/home/ayrton/.nvm/versions/node/v16.7.0/lib/node_modules/npm/lib/publish.js:120:7)
37 verbose statusCode 404
38 verbose pkgid @<scope>/<package>@0.1.0
39 verbose cwd [redacted]/<package>
40 verbose Linux 5.14.7-arch1-1
41 verbose argv "/home/ayrton/.nvm/versions/node/v16.7.0/bin/node" "/home/ayrton/.nvm/versions/node/v16.7.0/bin/npm" "publish" "--ignore-scripts" "<scope>-<package>-0.1.0.tgz" "--no-git-checks"
42 verbose node v16.7.0
43 verbose npm  v7.20.3
44 error code E404
45 error 404 Not Found - PUT https://[redacted]/@<scope>%2f<package> - no such package available
46 error 404
47 error 404 '@<scope>/<package>@0.1.0' is not in the npm registry.
48 error 404 You should bug the author to publish it (or use the name yourself!)
49 error 404 Note that you can also install from a
50 error 404 tarball, folder, http url, or git url.
51 verbose exit 1
```

My config:
```
storage: ./storage
auth:
  ldap:
    type: ldap
    # Only required if you are fetching groups that do not have a "cn" property. defaults to "cn" 
    #groupNameAttribute: "ou"
    # Optional, default false. 
    cache:
      # max credentials to cache (default to 100 if cache is enabled) 
      size: 100
      # cache expiration in seconds (default to 300 if cache is enabled) 
      expire: 300
    client_options:
      [redacted]
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@<scope>/*":
    access: $authenticated
    publish: $authenticated
  "@universalis/*":
    access: $authenticated
    publish: $authenticated
  "**":
    proxy: npmjs
logs:
  - { type: stdout, fromat: pretty, level: http }
web:
  enable: true
  title: Universalis
  logo: logo.png
  scope: universalis
listen:
  - 0.0.0.0:4873
security:
  api:
    legacy: false
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
      verify:
        algorithm:
        expiresIn:
        notBefore:
        ignoreExpiration:
        maxAge:
        clockTimestamp:
  web:
    sign:
      expiresIn: 7d
store:
  offline-storage:
```

Package.json
```json
{
  "name": "@<scope>/<package>",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "devDependencies": {},
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "wasm-pack build --target web",
    "postinstall": "wasm-pack build --target web"
  },
  "author": "Ayrton Sparling",
  "license": "MIT",
  "publishConfig": {
    "registry": "https://[redacted]"
  }
}

```

I'll see if I can put together an example project.

**Comment by FallingSnow** [comment]
Here is the test repo. Error occurs for me when using it.

https://github.com/FallingSnow/Verdaccio-2096

**Comment by juanpicado** [comment]
The permissions issues are explained here
https://verdaccio.org/docs/docker#running-verdaccio-using-docker
and
https://verdaccio.org/blog/2019/05/13/the-new-docker-image-verdaccio-4#security

**Comment by ganeshsacharya** [comment]
> https://verdaccio.org/blog/2019/05/13/the-new-docker-image-verdaccio-4#security

I hit the same issue as well. This point helped me.
My setup is verdaccio running as a Node Process from pm2 and nginx reverse proxy server the content over SSL.

What i did was to move the storage and plugins folders to a directory which i know has access processes.

**Comment by leppaott** [comment]
Same issue using verdaccio dockerhub 6 image and don't even have a volume on storage?

**Comment by mikicho** [comment]
For me, it was a permission problem because I used (docker) mount.
I think we may want to improve the error message here (at least in the logs), and maybe send `internal error` to the client

**Comment by mbtools** [comment]
https://github.com/verdaccio/verdaccio/pull/4913 takes care of 404 issues related to scoped tarballs but it's not in 5x/6x yet

**Comment by juanpicado** [comment]
This weekend is out check on Monday

**Comment by juanpicado** [comment]
fixed at https://github.com/verdaccio/verdaccio/releases/tag/v6.0.2

**Comment by melMass** [comment]
I'm still experiencing this in 6.0.2 using the node api:

```sh
npm notice total files: 25
npm notice
npm notice Publishing to https://xxx.xxx.com/ with tag latest and default access
npm error code E404
npm error 404 Not Found - PUT https://xxx.xxx.com/@mtb%2fts-plus - no such package available
npm error 404
npm error 404  '@mtb/ts-plus@0.0.2' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
```

That also looks similar to #2096

**Comment by mbtools** [comment]
Please open a new issue with steps/code to reproduce

**Comment by melMass** [comment]
> Please open a new issue with steps/code to reproduce

Thanks, it's literally exactly the errors described by others in this thread.

In case it helps others googling the issue around:

After debugging it for quite a while I think I nailed the issue, it's a server configuration issue (related to [AllowEncodedSlashes](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes)), without it slashes aren't properly supported.

**Comment by mbtools** [comment]
That is an excellent find, @melMass! Indeed, encoded slashes must be allowed

**Comment by kelyaenn** [comment]
I encountered the same issue with latest versions of traefik.
To fix it the traefik config must be edited to add : 
```yaml
entryPoints:
  <name>:
    address: ":443"
    http:
      encodedCharacters:
        allowEncodedSlash: true
```
