### ISSUE TITLE
latest tag is incorrect

### ISSUE THREAD

**Issue by mlucool** [verdaccio/verdaccio#411]
#### My reason:
The latest tag listed is wrong for public libraries.

#### Steps to reproduce:
I noticed this via npm install -s immutable (npm 5). If you use a verdaccio library you get the rc version of immutable and if you use npmjs.org you the true latest tag 3.x

You can also verify this via the urls which at the time of this writing shows:
https://registry.npmjs.org/immutable
```
"_id":"immutable",
"_rev":"301-da1702370f366fb61a98d20142465e0c",
"name":"immutable",
"description":"Immutable Data Collections",
"dist-tags":{
   "latest":"3.8.2",
   "rc":"4.0.0-rc.9"
},
```
And my localhost:port/immutable shows:
```
  "name": "immutable",
  "_rev": "2322-1093671c0ff912d2",
  "dist-tags": {
    "latest": "4.0.0-rc.4",
    "rc": "4.0.0-rc.9"
  },
```

####  App Version:	
`2.6.3`. I am not sure if the previous version was correct, but `sinopia` was also wrong.

**Comment by mlucool** [comment]
I debugged this a little more and was not able to reproduce this from a clean slate. I think it was the data I copied from `sinopia` that is wrong somehow. Still, the feature request here would be to verify the current tags and as it is possible for them to change. Even if it was different, it should check what latest points to. See: https://docs.npmjs.com/cli/dist-tag

**Comment by juanpicado** [comment]
I moved this to next major release. We are working on it :)  thanks @mlucool for reporting

**Comment by juanpicado** [comment]
It should be fixed on `verdaccio@2.7.4`

**Comment by danielgindi** [comment]
Not fixed, "dist-tags" always contains only "latest". Publishing "alpha", "beta", "rc", whatever - all end up in "latest".

**Comment by juanpicado** [comment]
@danielgindi if you provide more detailed info. I'll be happy to dive into it.

**Comment by danielgindi** [comment]
Okay so I tried getting a verdaccio instance up and running,
Then publishing "package@1.0.0".
At this stage, 
`dist-tags` looks like this:
```
  "dist-tags": {
    "latest": "1.0.0"
  },
```

Now we're publishing "package@1.0.1-alpha.1",
and `dist-tags` looks like this:
```
  "dist-tags": {
    "latest": "1.0.1-alpha.1"
  },
```

So it's not only that the `latest` tag updates with tagged versions,
It's that the actual tags are not created, and we're left with only `latest`.

Tried with 2.7.4 and the latest beta.

Thank you!

**Comment by juanpicado** [comment]
Ok, you are missing the commands that you are using in order to publish. I'll assume is something like this:

```
npm publish package@1.0.0
```
the outcome of that is 
```
 "dist-tags": {
    "latest": "1.0.0"
  },
```
you are right. Then you publish again
```
npm publish package@1.0.1-alpha.1
```
Am I wrong? If you are doing that, `npm` use the tag `latest` as **default**.

The point is, if you want a new tag you have to specify it. Like this

```
npm publish package@1.0.1-alpha.1 --tag alpha
```
Then the outcome becomes like this

```
 "dist-tags": {
    "latest": "1.0.0",
    "alpha": "1.0.1-alpha.1"
  },
```
Is that what you want to achieve @mlucool  ?

**Comment by danielgindi** [comment]
I do not actually specify the version in the `publish` command, it is specified in the `package.json`.
It is my understand that the tag in `npm` is deduced from package.json automatically, am I wrong?

**Comment by danielgindi** [comment]
Yeah so that's what's not working. If `package.json` specified `{"version":"1.0.0-alpha.1"}`, it is still published to `latest`.
Now I read npm documentation again, and they do say that `--tag alpha` should be specified in this case.
It's weird that semver's tag part lives in a different namespace than the `dist-tags`, but I'm okay with that as it actually gives me more flexibility.

You made things more clear. Thank you! :-)

**Comment by jomel** [comment]
@danielgindi Has this been fixed? The issue is closed since 28 Jan, but on 12 Mar you seem to suggest that it's still not working...

**Comment by juanpicado** [comment]
@jomel AFAIK is fixed.
