### ISSUE TITLE
Setting showRaw to false in Verdaccio is not working

### ISSUE THREAD

**Issue by drizzlesconsin** [verdaccio/verdaccio#4736]
**Your Environment**
  
 * **verdaccio version**: 5.31.1
 * **node version**: 18.19.2
 * **package manager**: npm@10.2.3
 * **os**: linux
 * **platform**: [npm, docker, helm, other]

**Describe the bug**

Settings such as showInfo: false, showSettings: false, and showFooter: false are working, but showRaw: false is not.

then 

I have already configured the favicon, but the generated link is still: 
`<link rel="icon" href="https://xxx.xxx.xx/-/static/favicon.ico"/>`

**To Reproduce**

**Expected behavior**

**Screenshots, server logs, package manager log**

<img width="510" alt="image" src="https://github.com/user-attachments/assets/6538dfb9-f2d3-4519-8b46-3d9ef272337b">

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```yaml
web:
  title: NPM
  logo: https://xx.xx.xx/logo.png
  favicon: https://xx.xx.xx/logo.png
  primary_color: '#8886f3'
  gravatar: true
  pkgManagers:
    - npm
    - pnpm
  showInfo: false
  showSettings: false
  showFooter: false
  showRaw: false
  showDownloadTarball: false

auth:
  htpasswd:
    file: ./htpasswd
```

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)

I checked the debug output with `debug('template %o', template);`, and the options do not include the showRaw field.

```
template { manifest: { js: [ 'runtime.js', 'vendors.js', 'main.js' ] }, options: { showInfo: false, showSettings: false, showThemeSwitch: undefined, showFooter: false, showSearch: undefined, showDownloadTarball: false, darkMode: false, url_prefix: undefined, basename: '/', base: 'xxx', primaryColor: '#333333', version: '5.31.1', logo: 'xxx', flags: { searchRemote: false, changePassword: false }, login: true, pkgManagers: [ 'npm', 'pnpm' ], title: 'xxx', scope: '', language: '', hideDeprecatedVersions: false }, scriptsBodyAfter: [], scriptsbodyBefore: undefined }
```

- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
Probably fixed here https://github.com/verdaccio/verdaccio/commit/0867aec8ff1c7a8e7ce85c015ad205c4130749b9 and https://github.com/verdaccio/verdaccio/pull/4687

**Comment by drizzlesconsin** [comment]
The value of the favicon is the same as the logo, both are .png files, but the page still shows `https://npm.xxx.com//-/static/favicon.ico`.
```
 logo: https://xx.xx.xx/logo.png
favicon: https://xx.xx.xx/logo.png
```

<img width="530" alt="image" src="https://github.com/user-attachments/assets/c56aaee4-133a-4a4d-b665-b8bd292d6229">

**Comment by mbtools** [comment]
Logos and favicon are handled a bit differently (favicon has a redirect).  But there is indeed a but in metadata link. PR coming a bit later.
